import React from "react"
import { ReactQueryProvider } from "~/providers"
import type { Metadata } from "next"

import "../globals.css"

export const metadata: Metadata = {
	title: "CardQuizzer",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<ReactQueryProvider>{children}</ReactQueryProvider>
			</body>
		</html>
	)
}
