name: Build & Publish Docker image

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: khalid95/card-quizzler-frontend

      - name: 'Create env file'
        run: |
          touch .env
          echo NEXT_PUBLIC_APP_URL=${{ secrets.APP_URL }} >> .env
          echo NEXT_PUBLIC_API_URL=${{ secrets.API_URL }} >> .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            NEXT_PUBLIC_APP_URL=${{ secrets.APP_URL }}
            NEXT_PUBLIC_API_URL=${{ secrets.API_URL }}
