name: Build & Publish Docker image

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: khalid95/card-quizzler-frontend

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t khalid95/card-quizzler-frontend:latest .
          docker run khalid95/card-quizzler-frontend:latest pnpm run build

      - name: Capture build logs
        if: ${{ steps.build-image.outcome != 'success' }}
        run: |
          echo "Build failed, capturing logs..."
          docker logs $(docker ps -q --filter ancestor=khalid95/card-quizzler-frontend:latest)

      - name: Push Docker image
        if: ${{ steps.build-image.outcome == 'success' }}
        run: |
          docker push khalid95/card-quizzler-frontend:latest
